import { PackSize } from '@/models/packSize';

export const Data: PackSize[] = [
  {
    id: '1',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    unitOfMeasure: 'lbs',
    abbreviation: 'lbs',
    min: 1,
    max: 10,
    packStyleId: '1',
    isActive: false,
  },
  {
    id: '2',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    unitOfMeasure: 'lbs',
    abbreviation: 'lbs',
    min: 1,
    max: 10,
    packStyleId: '1',
    isActive: false,
  },
  {
    id: '3',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    unitOfMeasure: 'lbs',
    abbreviation: 'lbs',
    min: 1,
    max: 10,
    packStyleId: '1',
    isActive: false,
  },
  {
    id: '4',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    unitOfMeasure: 'lbs',
    abbreviation: 'lbs',
    min: 1,
    max: 10,
    packStyleId: '1',
    isActive: false,
  },
  {
    id: '5',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    unitOfMeasure: 'lbs',
    abbreviation: 'lbs',
    min: 1,
    max: 10,
    packStyleId: '1',
    isActive: false,
  },
  {
    id: '6',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    unitOfMeasure: 'lbs',
    abbreviation: 'lbs',
    min: 1,
    max: 10,
    packStyleId: '1',
    isActive: false,
  },
];
