export const GROWING_METHOD_QUERY_KEYS = {
  GET_GROWING_METHODS: 'GET_GROWING_METHODS',
  GET_GROWING_METHOD_BY_ID: 'GET_GROWING_METHOD_BY_ID',
  CREATE_GROWING_METHOD: 'CREATE_GROWING_METHOD',
  UPDATE_GROWING_METHOD: 'UPDATE_GROWING_METHOD',
  DELETE_GROWING_METHOD: 'DELETE_GROWING_METHOD',
}