export const ORDERS_QUERY_KEYS = {
  GET_ORDERS: 'GET_ORDERS',
  GET_ORDER_DETAIL: 'GET_ORDER_DETAIL',
  CREATE_ORDER: 'CREATE_ORDER',
  UPDATE_ORDER: 'UPDATE_ORDER',
  DELETE_ORDER: 'DELETE_ORDER',
}