export const PACK_SIZE_QUERY_KEYS = {
  GET_PACK_SIZES: 'GET_PACK_SIZES',
  GET_PACK_SIZE_BY_ID: 'GET_PACK_SIZE_BY_ID',
  CREATE_PACK_SIZE: 'CREATE_PACK_SIZE',
  UPDATE_PACK_SIZE: 'UPDATE_PACK_SIZE',
  DELETE_PACK_SIZE: 'DELETE_PACK_SIZE',
}