export const PACK_STYLE_QUERY_KEYS = {
  GET_PACK_STYLES: 'GET_PACK_STYLES',
  GET_PACK_STYLE_BY_ID: 'GET_PACK_STYLE_BY_ID',
  CREATE_PACK_STYLE: 'CREATE_PACK_STYLE',
  UPDATE_PACK_STYLE: 'UPDATE_PACK_STYLE',
  DELETE_PACK_STYLE: 'DELETE_PACK_STYLE',
}