export const USERS_QUERY_KEYS = {
  GET_USERS: 'GET_USERS',
  GET_USER_BY_ID: 'GET_USER_BY_ID',
  GET_USER_TYPES: 'GET_USER_TYPES',
  GET_USER_STATUSES: 'GET_USER_STATUSES',
  CREATE_USER: 'CREATE_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
}