import { Brand } from '@/models/brand';

export const ProductCatalogData: Brand[] = [
  {
    id: '1',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    commodity: 'Lorem ipsum dolor sit amet',
    variety: 'Lorem ipsum dolor sit amet',
    subVariety: 'Lorem ipsum dolor sit amet',
    plu: 'Lorem ipsum dolor sit amet',
    growingMethod: 1,
    isActive: false,
  },
  {
    id: '2',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    commodity: 'Lorem ipsum dolor sit amet',
    variety: 'Lorem ipsum dolor sit amet',
    subVariety: 'Lorem ipsum dolor sit amet',
    plu: 'Lorem ipsum dolor sit amet',
    growingMethod: 1,
    isActive: true,
  },
  {
    id: '3',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    commodity: 'Lorem ipsum dolor sit amet',
    variety: 'Lorem ipsum dolor sit amet',
    subVariety: 'Lorem ipsum dolor sit amet',
    plu: 'Lorem ipsum dolor sit amet',
    growingMethod: 1,
    isActive: false,
  },
  {
    id: '4',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    commodity: 'Lorem ipsum dolor sit amet',
    variety: 'Lorem ipsum dolor sit amet',
    subVariety: 'Lorem ipsum dolor sit amet',
    plu: 'Lorem ipsum dolor sit amet',
    growingMethod: 1,
    isActive: true,
  },
  {
    id: '5',
    name: 'Apple',
    description: 'Lorem ipsum dolor sit amet',
    commodity: 'Lorem ipsum dolor sit amet',
    variety: 'Lorem ipsum dolor sit amet',
    subVariety: 'Lorem ipsum dolor sit amet',
    plu: 'Lorem ipsum dolor sit amet',
    growingMethod: 1,
    isActive: true,
  },
];
